// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

public partial class FlashCardLearnContext : DbContext
{
    public FlashCardLearnContext(DbContextOptions<FlashCardLearnContext> options)
        : base(options)
    {
    }

    public FlashCardLearnContext()
    {
        
    }

    public virtual DbSet<FlashCard> FlashCards { get; set; }

    public virtual DbSet<FlashCardSet> FlashCardSets { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Data Source=PHUC\\PHUC;Initial Catalog=FlashCardLearn;User ID=sa;Password=123456789;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True;Application Intent=ReadWrite;Multi Subnet Failover=False");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FlashCard>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FlashCar__3213E83F666D7250");

            entity.ToTable("FlashCard");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Answer)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("answer");
            entity.Property(e => e.FlashcardsetId).HasColumnName("flashcardset_id");
            entity.Property(e => e.Question)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("question");

            entity.HasOne(d => d.Flashcardset).WithMany(p => p.FlashCards)
                .HasForeignKey(d => d.FlashcardsetId)
                .HasConstraintName("FK__FlashCard__flash__267ABA7A");
        });

        modelBuilder.Entity<FlashCardSet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FlashCar__3213E83FE1539727");

            entity.ToTable("FlashCardSet");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Progress).HasColumnName("progress");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("title");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}