// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class FlashCard
{
    public int Id { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public int FlashcardsetId { get; set; }

    public virtual FlashCardSet Flashcardset { get; set; }
}