// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Repositories.Models;

public partial class FlashCardSet
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? Progress { get; set; } = 0;

    public virtual ICollection<FlashCard> FlashCards { get; set; } = new List<FlashCard>();
}